apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-memcached
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - name: memcached-client
      port: 11211
      targetPort: 11211
    - name: exporter-http-metrics
      port: 9150
      targetPort: 9150
  selector:
    app: {{ .Release.Name }}-memcached