apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  overrides.yaml: |
    overrides: {}
  tempo.yaml: |
    auth_enabled: false
    compactor: null
    distributor:
        receivers:
            zipkin: null
    ingester:
        lifecycler:
            ring:
                replication_factor: 2
    memberlist:
        abort_if_cluster_join_fails: false
        bind_port: 7946
        join_members:
          - {{ .Release.Name }}-gossip-ring.{{ .Release.Namespace }}.svc.cluster.local:7946
    overrides:
        ingestion_rate_limit: 10000000
        max_traces_per_user: 0
        per_tenant_override_config: /conf/overrides.yaml
    server:
        http_listen_port: 3100
    storage:
        trace:
    {{- toYaml .Values.backend | nindent 12 }}
            blocklist_poll: 5m
            memcached:
                consistent_hash: true
                host: {{ .Release.Name }}-memcached.{{ .Release.Namespace }}.svc.cluster.local
                service: memcached-client
                timeout: 1s
            pool:
                queue_depth: 2000
            wal:
                path: /var/tempo/wal