apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-querier
  namespace: {{ .Release.Namespace }}
data:
  tempo.yaml: |
    auth_enabled: false
    memberlist:
      abort_if_cluster_join_fails: false
      bind_port: 7946
      join_members:
        - {{ .Release.Name }}-gossip-ring.{{ .Release.Namespace }}.svc.cluster.local:7946
    overrides:
      per_tenant_override_config: /conf/overrides.yaml
    server:
      http_listen_port: 3100
      log_level: debug
    storage:
        trace:
    {{- toYaml .Values.backend | nindent 12 }}
            blocklist_poll: 5m
            memcached:
                consistent_hash: true
                host: {{ .Release.Name }}-memcached.{{ .Release.Namespace }}.svc.cluster.local
                service: memcached-client
                timeout: 1s
            pool:
                max_workers: 200
                queue_depth: 2000
            wal:
                path: /var/tempo/wal