apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-querier
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 10
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Release.Name }}-querier
      tempo-gossip-member: "true"
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-querier
        tempo-gossip-member: "true"
    spec:
      containers:
        - args:
            - -target=querier
            - -config.file=/conf/tempo.yaml
            - -mem-ballast-size-mbs=1024
          image: {{ .Values.tempo.image }}:{{ .Values.tempo.tag }}
          imagePullPolicy: IfNotPresent
          name: querier
          ports:
            - containerPort: 3100
              name: prom-metrics
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          volumeMounts:
            - mountPath: /conf
              name: tempo-conf
        - args:
            - --query.base-path=/
            - --grpc-storage-plugin.configuration-file=/conf/tempo-query.yaml
            - --query.bearer-token-propagation=true
          image: {{ .Values.tempo.query.image }}:{{ .Values.tempo.tag }}
          imagePullPolicy: IfNotPresent
          name: tempo-query
          ports:
            - containerPort: 16686
              name: jaeger-ui
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          volumeMounts:
            - mountPath: /conf
              name: tempo-query-conf
      volumes:
        - configMap:
            name: {{ .Release.Name }}-query
          name: tempo-query-conf
        - configMap:
            name: {{ .Release.Name }}-querier
          name: tempo-conf