apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-compactor
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 10
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-compactor
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-compactor
    spec:
      containers:
        - args:
            - -target=compactor
            - -config.file=/conf/tempo.yaml
            - -mem-ballast-size-mbs=1024
          image: {{ .Values.tempo.image }}:{{ .Values.tempo.tag }}
          imagePullPolicy: IfNotPresent
          name: compactor
          ports:
            - containerPort: 3100
              name: prom-metrics
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
          volumeMounts:
            - mountPath: /conf
              name: tempo-conf
      volumes:
        - name: tempo-conf
          configMap:
            name: {{ .Release.Name }}-compactor