apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-querier
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http-tempo-query-jaeger-ui
      port: 16686
      targetPort: 16686
    - name: http-querier-prom-metrics
      port: 3100
      targetPort: 3100
  selector:
    app: {{ .Release.Name }}-querier