apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-ingester
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 3
  serviceName: {{ .Release.Name }}-ingester
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ingester
      tempo-gossip-member: "true"
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ingester
        tempo-gossip-member: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ .Release.Name }}-ingester
              topologyKey: kubernetes.io/hostname
      containers:
        - args:
            - -target=ingester
            - -config.file=/conf/tempo.yaml
            - -mem-ballast-size-mbs=1024
          image: {{ .Values.tempo.image }}:{{ .Values.tempo.tag }}
          imagePullPolicy: IfNotPresent
          name: ingester
          ports:
            - containerPort: 3100
              name: prom-metrics
          resources:
            requests:
              cpu: 1m
              memory: 1.5Gi
          volumeMounts:
            - mountPath: /conf
              name: tempo-conf
            - mountPath: /var/tempo
              name: {{ .Release.Name }}-ingester-data
      volumes:
        - configMap:
            name: {{ .Release.Name }}
          name: tempo-conf
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        labels:
          app: {{ .Release.Name }}-ingester
        name: {{ .Release.Name }}-ingester-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: local-path