name: Docker publish

on:
  push:
    paths:
      - .github/workflows/docker-publish-images.yml
      - .gitmodules
      - Makefile
    branches:
      - 'master'

jobs:
  docker-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component:
          - tempo
          - tempo-query
          - tempo-vulture

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Publish images
        run: |
          make dep
          make buildx COMPONENT=${{ matrix.component }}